/* Execution Context Object has three properties:
1.Variable Object (VO) : Function arguments, inner variable declarations,function declarations
2.Scope Chain: Current VO and Parent VO
3.This variable: */

/* Creation phase:
1.Creation of the VO
2.Creation of the scope chain
3.Determine value of the 'this' variable

Execution phase:
The code of the function generated by the execution context is ran line by line */

/* Creation of the Variable Object:
1. The argument object is created, containing all the arguments that were passed into the function.
HOISTING:
2. Code is scanned for function declarations: for each function, a property is created in the Variable Object, pointing to the function.
3. Code is scanned for variable declarations: for each variable, a property is created in the Variable Object, and set to undefined. */
